<?php



/**
 * Skeleton subclass for performing query and update operations on the 'event' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Mon Feb 27 19:13:43 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class EventQuery extends BaseEventQuery {

} // EventQuery
